# You can use 'kubectl describe <kind> <name>' to see the configs details.

# Config map with nested key-value pairs
apiVersion: v1
kind: ConfigMap
metadata:
  name: player-config
data:
  # Key-value pairs for player configuration
  player_lives: "5"
  properties_file_name: "ui.properties"

  # Nested key-value pairs
  base.properties: |
    enemy.types=zombie,alien,robot
    player.max_lives=10
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true

  # The configMap can be anything, for example an nginx.conf file. 
  # We could then mount this configMap as a volume and use it as the nginx configuration file.
  # Example mounting of this configMap as a volume:
  # volumes:
  # - name: nginx-config-volume # define the name of the created volume
  #   configMap:
  #     name: nginx-config # specify the name of the configMap to use as the source of the volume
  # volumeMounts:
  # - name: nginx-config-volume # specify the name of the volume to mount
  #   mountPath: /etc/nginx # specify the path inside the container where the volume should be mounted
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
        }
      }
    }
    ...

---

# Config map with flat key-value pairs
apiVersion: v1
kind: ConfigMap
metadata:
  name: player-config-flat
data:
  # Key-value pairs for player configuration
  KEY1: value1
  KEY2: value2
  KEY3: value3

---

# You can remove this config from file after creating the secret, as it contains sensitive information. You can also setup correct permissions for the file/secret object modification/access.
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
# base64 encoded values, can use `echo -n 'value' | base64` to encode 
data:
  username: YWRtaW4=
  password: YWRtaW5wYXNzd29yZA==

---

# Inside the container, you can run echo $<NAME>, e.g. echo $PLAYER_LIVES, or printenv to see all env variables.
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-demo
spec:
  containers:
    - name: config-demo
      image: alpine
      command: ["sleep", "3600"]
      # Defining keys from ConfigMap and Secret as environment variables in the container
      env:
        # Define the environment variable
        - name: PLAYER_LIVES
          valueFrom:
            configMapKeyRef:
              name: player-config  # The object this value comes from.
              key: player_lives # The key to fetch.
        - name: PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: player-config
              key: properties_file_name
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: password
      # Directly adding the entire flat configMap/secret as environment variables
      envFrom:
        - configMapRef:
            name: player-config-flat
        - secretRef:
            name: example-secret

---

# If something went wrong with creating the volumes, you can check that with kubectl describe.
# The volume is mounted inside the container. You can run kubectl exec, cd into the mounted path and run ls/cat to see the contents of the volume.
apiVersion: v1
kind: Pod
metadata:
  name: vol-config-pod-demo
spec:
  containers:
    - name: vol-config-demo
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: player-map
        mountPath: /etc/config/configMap
      - name: player-secret
        mountPath: /etc/config/secret
  volumes:
    # We set volumes at the Pod level, then mount them into containers inside that Pod
    - name: player-map
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: player-config
    - name: player-secret
      secret:
        secretName: example-secret

