apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-http
spec:
  containers:
    - name: liveness-nginx
      image: k8s.gcr.io/nginx-slim:0.8
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5 # wait for 5 seconds before starting the health checks
        periodSeconds: 10 # check every 10 seconds
        failureThreshold: 3 # if the check fails 3 times, the container will be restarted
        successThreshold: 1 # if the check succeeds once, the container is considered healthy
        timeoutSeconds: 1 # if the check takes longer than 1 second, it is considered a failure

# ---

apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-exec
spec:
  containers:
    - name: liveness-probe-exec
      image: busybox
      # Command to run on container startup.
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          # checks if the file /tmp/healthy exists.
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 10
        # Alternatively, you can use an HTTP GET request for the liveness probe instead of an exec command.

          