apiVersion: v1
kind: Pod
metadata:
  name: restart-always-pod
spec:
  restartPolicy: Always # This one will restart the container, as sleep 20 will exit with code 0, which is considered a success
  containers:
    - name: app
      image: alpine
      command: ["sleep", "20"]

---
apiVersion: v1
kind: Pod
metadata:
  name: restart-onfailure-pod
spec:
  restartPolicy: OnFailure # This one will not restart the container, as sleep 20 will exit with code 0, which is considered a success
  containers:
    - name: app
      image: alpine
      command: ["sleep", "20"]

---
apiVersion: v1
kind: Pod
metadata:
  name: restart-never-pod
spec:
  restartPolicy: Never # This one will not restart the container, even if it fails
  containers:
    - name: app
      image: alpine
      command: ["sleep", "20"]
      # command: ["sleep", "20", "&&", "exit", "1"] 